# @file        .github/workflows/ci.yml
# @author      Brandon Christie <bchristie.dev@gmail.com>

name: ci

on:
  push:
    branches: [main]

jobs:
  deno:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [2.2.x, 2.3.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno v${{ matrix.deno-version }}
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}
          cache: true

      - name: Run tests
        run: deno test --config tests/deno/deno.json --shuffle --parallel tests/deno

  node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 24.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test-node
