# @file        .github/workflows/ci.yml
# @author      Brandon Christie <bchristie.dev@gmail.com>

name: ci

on:
  push:
    branches: [main]

jobs:
  deno:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [2.6.x, 2.7.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Deno v${{ matrix.deno-version }}
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}
          cache: true

      - name: Run tests
        run: grep -oP '(?<="test:deno":\s").+(?=",)' package.json | bash

  node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x, 25.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node v${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:node
